# Generated by Django 3.0.7 on 2020-06-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200626_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
