# Generated by Django 3.0.7 on 2020-06-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='Post',
        ),
    ]
