# Generated by Django 3.0.7 on 2020-06-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200614_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='userpost_pics'),
        ),
    ]
